### ISSUE TITLE
Can't compile asset pipeline on Digital Ocean droplet

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#22]
Stylesheets and javascript are not working. 
When I view-page-source on the app html, the linked resource files are not there.

I think that's because they have to be compiled from their scss / coffeescript sources. 

I think I should be able to set a few environment variables then run "rake assets:precompile", and that should produce the missing files.

But it doesn't work. Sometimes when I run "rake assets:precompile" it hangs the cloud computer - it becomes unresponsive, just sits there, all my ssh connections go dead, the only thing I can do is ping the server. Othertimes it crashes out after about 10s with the cryptic backtrace below. 

Any idea what's wrong that asset compilation should fail? Any ideas on this cryptic error message?

% *export RAILS_ENV=production*
% *rake assets:precompile -v*
`
rake aborted!
ExecJS::RuntimeError: 
(execjs):1
/usr/local/rvm/gems/ruby-2.2.1/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:214:in 'exec_runtime'
/usr/local/rvm/gems/ruby-2.2.1/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:39:in 'exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:21:in 'eval'
/usr/local/rvm/gems/ruby-2.2.1/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:46:in 'call'
/usr/local/rvm/gems/ruby-2.2.1/gems/uglifier-2.7.1/lib/uglifier.rb:212:in 'run_uglifyjs'
/usr/local/rvm/gems/ruby-2.2.1/gems/uglifier-2.7.1/lib/uglifier.rb:179:in 'compile'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/uglifier_compressor.rb:52:in 'call'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/uglifier_compressor.rb:28:in 'call'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:75:in 'call_processor'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:57:in 'block in call_processors'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in 'reverse_each'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in 'call_processors'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/loader.rb:86:in 'load_asset_by_uri'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/loader.rb:45:in 'block in load'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/loader.rb:155:in 'fetch_asset_from_dependency_cache'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/loader.rb:38:in 'load'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:20:in 'block in initialize'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in 'yield'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in 'load'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/base.rb:63:in 'find_asset'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/base.rb:70:in 'find_all_linked_assets'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:138:in 'block in find'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:114:in 'block (2 levels) in logical_paths'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:223:in 'block in stat_tree'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:207:in 'block in stat_directory'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in 'each'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in 'stat_directory'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:222:in 'stat_tree'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in 'each'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in 'block in logical_paths'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in 'each'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in 'logical_paths'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:136:in 'find'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:162:in 'compile'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in 'block (3 levels) in define'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-3.2.0/lib/rake/sprocketstask.rb:147:in 'with_logger'
/usr/local/rvm/gems/ruby-2.2.1/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in 'block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)`

**Comment by dcmorse** [comment]
Oooh, I got a new error message:
`% rake assets:precompile

#
# Fatal error in Evacuation
# Allocation failed - process out of memory
#
`

**Comment by dcmorse** [comment]
It was the system running out of memory. Adding lots of swap fixed it.
